files = [ "VME64xCore_NoIpTop.vhd",
          "VME_bus.vhd",
          "VME_CR_pack.vhd",
          "VME_CSR_pack.vhd",
          "VME_pack.vhd",
          "wishbone_pkg.vhd",
          "TrueDpBlockRam.vhd",
          "swapper.vhd",
          "SharedComps.vhd",
          "IRQ_Controller.vhd",
          "genram_pkg.vhd",
          "gen_buff.vhd",
          "FIFO.vhd",
          "DpBlockRam.vhd",
          "common_components.vhd",
          "Buff.vhd"]
